# Generated by Django 3.2.9 on 2021-11-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('1', 'High'), ('2', 'Medium'), ('3', 'Low')], max_length=6),
        ),
    ]
