# Generated by Django 3.2.9 on 2021-11-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='N', max_length=3),
        ),
    ]
