# Generated by Django 3.2.9 on 2021-11-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_rename_labels_task_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default=0, max_length=3),
        ),
    ]
