# Generated by Django 3.2.9 on 2021-11-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[(1, 'Yes'), (0, 'No')], default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], max_length=6),
        ),
    ]
